### ISSUE TITLE
[Done]When entering the game, the game crashed

### ISSUE THREAD

**Issue by FastShortcuts** [MCPluginbox/MCPluginbox#1]

**Comment by abcSKY666** [comment]
give me your mcpb version and client version

**Comment by FastShortcuts** [comment]
1.23 1.0.6-fix

**Comment by abcSKY666** [comment]
Please copy the error code, when you click the logo, it will display on your screen.

**Comment by FastShortcuts** [comment]
(-1029)Memory error

**Comment by abcSKY666** [comment]
thanks, we will check and fix it in next release.
